{% set version = "1.0.5" %}

package:
  name: dask-sphinx-theme
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-sphinx-theme/dask_sphinx_theme-{{ version }}.tar.gz
  sha256: e15b58e7bd23847c6870da3be5c8bcaa365ef9dd77f6039bc5a321d099f0ef7c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx_rtd_theme

test:
  imports:
    - dask_sphinx_theme

about:
  home: https://github.com/dask/dask-sphinx-theme
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Dask theme for Sphinx'

extra:
  recipe-maintainers:
    - jakirkham
    - mrocklin
