{% set version = "1.3.0" %}

package:
  name: dask-sphinx-theme
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-sphinx-theme/dask_sphinx_theme-{{ version }}.tar.gz
  sha256: cbb136fe12ee2cd17c183a520506c98c9881950f484d394fcdfaf39d0be38f9a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx_rtd_theme

test:
  imports:
    - dask_sphinx_theme

about:
  home: https://github.com/dask/dask-sphinx-theme
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Dask theme for Sphinx'

extra:
  recipe-maintainers:
    - jakirkham
    - mrocklin
    - jrbourbeau
