{% set version = "1.3.6" %}

package:
  name: dask-sphinx-theme
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-sphinx-theme/dask_sphinx_theme-{{ version }}.tar.gz
  sha256: 34cbc99a0b83ddddf811b637981d0609013d56010f2d99ecc77315d71cfdce44

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sphinx_rtd_theme >=0.5.2

test:
  imports:
    - dask_sphinx_theme

about:
  home: https://github.com/dask/dask-sphinx-theme
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Dask theme for Sphinx

extra:
  recipe-maintainers:
    - jakirkham
    - mrocklin
    - jrbourbeau
