{% set version = "2.0.3" %}

package:
  name: dask-sphinx-theme
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-sphinx-theme/dask_sphinx_theme-{{ version }}.tar.gz
  sha256: b52323381d471408ae8959dfb7b5b1dd546b27107813159cff4ce30cdfd68dcd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx-book-theme 0.2.0

test:
  imports:
    - dask_sphinx_theme

about:
  home: https://github.com/dask/dask-sphinx-theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Dask theme for Sphinx

extra:
  recipe-maintainers:
    - jakirkham
    - mrocklin
    - jrbourbeau
    - jacobtomlinson
