travis:
  secure:
    BINSTAR_TOKEN: aAGv1emwAKC6itNwKws9+tCBGVGSVCVcTSlff+mPFoEBkhoH5D0lWjGCK78HdJi+zoAH4upNQ+kbm6YaTedCFngYH7XNL9bwyBhpxfi5Jhh7wvjsF3yz9Oe0svEjkh3Qg3SHRb5joxYC81llU+yxFpuNtKhAQs9aFzj8IzNspI5RzaEsTv0Jfb5/E7b1JSzUQ4VkZ6iwq2NTXCKeTpZMoHUt4XvFiY0LifayepsoQtalVBH4Qv/qHlsKzWIb41eFOd85o9EX7l7bCaTSeeKFQyvVSZWYM5ZRUi+KKKKfHu7XBzJjsrjHT7/2geTgZIMr3qgXUxYz3brqPoTzRzkuU4BWrtIRhlfjzsprZpHWxTPuoySkl16hzGrRHVWyVXosazGtQto/aL6nisbhlvNawVwWU5xupluD4puHLbmgJGSUuxMAc5F6b+Xma2XomAHIeJ2gcnD4DsoglPaaemFQLx+1eWe8er+Vii87v+QYGCAGJVMewfq81x/xRhd68KG0AR1FH5CyN2wAxPypFlFiuiFH71chxc9zUB8DqMW42YROb/wJ9Y2wobtgHITexFXC5vDf5UnLqBD4bfPbkOnN74Da+1u9JXYbjc6fwSTMn0pAGtmnRP916Zk/pME1kapWHwcQGdBRDslsP8T7oHx9w3ABqBxTdWSysaHeqXlV0x8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
